# ZONE DE RATE LIMITING (Control 1)
limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

server {
    listen 443 ssl;
    server_name td4.local;

    ssl_certificate /etc/nginx/ssl/server.crt;
    ssl_certificate_key /etc/nginx/ssl/server.key;

    # === HARDENING TLS (NIST SP 800-52 Rev.2) ===
    # On force TLS 1.2 et 1.3 uniquement
    ssl_protocols TLSv1.2 TLSv1.3;
    
    # Suites cryptographiques robustes (AEAD uniquement, pas de CBC)
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305';
    ssl_prefer_server_ciphers on;

    # === HSTS (HTTP Strict Transport Security) ===
    add_header Strict-Transport-Security "max-age=300" always;

    # === REQUEST FILTERING (Control 2) ===
    # Bloque les requêtes provenant d'un robot malveillant connu
    if ($http_user_agent ~* "BadBot") {
        return 403;
    }

    location / {
        root /var/www/html;
        index index.html index.nginx-debian.html;
    }

    # === ENDPOINT SOUS RATE LIMITING ===
    location /api {
        limit_req zone=api_limit burst=5 nodelay;
        default_type text/plain;
        return 200 "Bienvenue sur l'API securisee !\n";
    }
}