server {
    listen 443 ssl;
    server_name td4.local;

    ssl_certificate /etc/nginx/ssl/server.crt;
    ssl_certificate_key /etc/nginx/ssl/server.key;

    # CONFIGURATION VOLONTAIREMENT FAIBLE (BASELINE)
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers HIGH:MEDIUM:!aNULL;
    ssl_prefer_server_ciphers on;

    location / {
        root /var/www/html;
        index index.html index.nginx-debian.html;
    }
}